// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoPaHnOC_eRjFgN5vVEtmnYeEUK4pdG0',
    appId: '1:146975697415:web:b4710e50865141ec4b58a2',
    messagingSenderId: '146975697415',
    projectId: 'pharmamanagementsystem-dc5f1',
    authDomain: 'pharmamanagementsystem-dc5f1.firebaseapp.com',
    databaseURL: 'https://pharmamanagementsystem-dc5f1-default-rtdb.firebaseio.com',
    storageBucket: 'pharmamanagementsystem-dc5f1.appspot.com',
    measurementId: 'G-HKDZTRE0HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRXTRdiG3lTnuKB0YchbVbch5J6Ns6J0',
    appId: '1:146975697415:android:c93e6ae26ffe02874b58a2',
    messagingSenderId: '146975697415',
    projectId: 'pharmamanagementsystem-dc5f1',
    databaseURL: 'https://pharmamanagementsystem-dc5f1-default-rtdb.firebaseio.com',
    storageBucket: 'pharmamanagementsystem-dc5f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDECrqpz4nbz_gtoNCCeWealbm53f2aro',
    appId: '1:146975697415:ios:bd7105a0d27a174e4b58a2',
    messagingSenderId: '146975697415',
    projectId: 'pharmamanagementsystem-dc5f1',
    databaseURL: 'https://pharmamanagementsystem-dc5f1-default-rtdb.firebaseio.com',
    storageBucket: 'pharmamanagementsystem-dc5f1.appspot.com',
    androidClientId: '146975697415-lmmcot30irdg8kbb9qro2pa9fa64rops.apps.googleusercontent.com',
    iosClientId: '146975697415-ma45dhs238lnrj7ep12b5ed99v70tv64.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmamanagementsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDECrqpz4nbz_gtoNCCeWealbm53f2aro',
    appId: '1:146975697415:ios:bd7105a0d27a174e4b58a2',
    messagingSenderId: '146975697415',
    projectId: 'pharmamanagementsystem-dc5f1',
    databaseURL: 'https://pharmamanagementsystem-dc5f1-default-rtdb.firebaseio.com',
    storageBucket: 'pharmamanagementsystem-dc5f1.appspot.com',
    androidClientId: '146975697415-lmmcot30irdg8kbb9qro2pa9fa64rops.apps.googleusercontent.com',
    iosClientId: '146975697415-ma45dhs238lnrj7ep12b5ed99v70tv64.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmamanagementsystem',
  );
}
